system_name: Aina

Aina:
  model: ca-en
  revision: main
  beam_size: 5
  num_hypotheses: 5

SalamandraTA:
  src_lang: Catalan
  tgt_lang: Croatian
  model_id: BSC-LT/salamandraTA-2b
  beam_size: 5
  num_hypotheses: 5

MTEngine:
  MTengine: Aina
  #one of Marian, OpenNMT, Moses, GoogleTranslate, DeepL, Lucy, OpusMT, NLLB, Softcatalà, Apertium, Transformers, Aina, ctranslate2
  SLcode: hr
  TLcode: es
  multilingual: False
  #False or <2tgtlang> or any multilingual code used by the system.

MTUOCServer:
  port: 8000
  type: MTUOC
  #one of MTUOC, Moses, ModernMT, OpenNMT, NMTWizard
  verbosity_level: 4
  ONMT_url_root: "/translator"
  #specific configuration when acting as ONMT server
  log_file: log.log
  
Preprocess:
  checkistranslatable: True
  tokenize: False
  tokenizer: MTUOC_tokenizer_eng
  #one of None, MTUOC_tokenizer_xxx, Moses
  MosesTokenizerLang: en
  truecase: upper
  #one of always, never, upper
  truecaser: MTUOC
  #one of MTUOC, Moses
  truecaser_tokenizer: MTUOC_tokenizer_spa
  #one of None, MTUOC_tokenizer_xxx, Moses
  tcmodel: tc.ca
  MosesTokenizerLang: en
    
  use_MosesPunctNormalizer: False
  unescape_html: True
  fixencoding: True
  escapeforMoses: False

  remove_tags: False
  segment: False
  srxfiles: segment.srx
  srxlang: English
  strategy: bysegments
  #on of bysegments bychunks
  remove_control_characters: True
  remove_non_printable: True
  remove_non_latin_extended_chars: False
  remove_non_unicode_script_chars: True
  change_input_files: None
  change_input_delimiter: ;
  change_input_quote: '"'
  
  splitlongsegments: False
  maxlong: 10000
  separators: "; : ,"

Postprocess:
  restore_case: True
  restore_tags: True
  numeric_check: False
  change_output_files: None
  change_output_delimiter: ;
  change_output_quote: '"'
  change_translation_files: None
  change_translation_delimiter: ;
  change_translation_quote: '"'
  
  
Scoring:
  #sbert
  calculate_sbert: False
  sort_by_sbert: False
  sbert_model: LaBSE
  # LaBSE is the default model and one model should be stated
  
    
GetWordAlignments:
  type: None
  #one of None, fast_align
  tokenizerSL: MTUOC_tokenizer_spa
  #one of None, MTUOC_tokenizer_xxx, Moses
  tokenizerTL: MTUOC_tokenizer_cat
  #one of None, MTUOC_tokenizer_xxx, Moses
  tokenizerSLcode: es
  tokenizerTLcode: ca
  #if required by tokenizer
  fwd_params_file: align-es-ca_params
  fwd_err_file: align-es-ca_err
  rev_params_file: align-ca-es_params
  rev_err_file: align-ca-es_err
  
Marian:
  startMarianServer: True
  startMarianCommand: "./marian-server-GPU -m model.npz.best-cross-entropy.bin -v vocab-es.yml vocab-ca.yml -p 8250 --n-best --alignment hard --normalize 1 -b 20 --word-penalty 10 --max-length-factor 1.24 --quiet &"
  IP: localhost
  port: 8250
  subword_type: SentencePiece
  subword_model: spmodel.model



Transformers:
#use the same configuration for OpusMT
  model_path: fine-tuned-opusmt-EP-es-ca
  #model_path: Helsinki-NLP/opus-mt-es-ca
  beam_size: 5
  num_hypotheses: 5
  
NLLB:
  model: facebook/nllb-200-distilled-1.3B
  src_lang: hrv_Latn
  tgt_lang: fra_Latn
  beam_size: 5
  num_hypotheses: 5
  
Softcatala:
  model_dir: softcatala-eng-cat
  beam_size: 5
  num_hypotheses: 5
  
ctranslate2:
  translation_model: ./nllbOpenNMT/nllb-200-600M-ct2
  SL_spmodel: ./nllbOpenNMT/flores200_sacrebleu_tokenizer_spm.model
  TL_spmodel: ./nllbOpenNMT/flores200_sacrebleu_tokenizer_spm.model
  src_lang: spa_Latn
  tgt_lang: rus_Cyrl
  beam_size: 5
  num_hypotheses: 5
  device: cpu
  
Apertium:
  sl: spa
  tl: cat

