model_settings:
  name: "google/madlad400-3b-mt"
  device: "cuda"  # O "cpu"

lang_settings:
  dynamic: true           # Si és true, el tag ha de venir dins del segment (ex: "<2es> Hola")
  default_target_tag: "<2en>" # Tag per defecte si dynamic és false o no es troba el tag

generation_params:
  max_new_tokens: 512
  temperature: 0.1
  repetition_penalty: 1.2
  num_beams: 5
  no_repeat_ngram_size: 3
