prompt_settings:
  template: "Translate the following text from Spanish into English.\nSpanish: {SLsegment}\nEnglish:"
  #Salamandra text = f"Translate the following text from {source} into {target}.\n{source}: {sentence} \n{target}:"
  json_key: None
  regex_pattern: None   

model_settings:
  name: "BSC-LT/salamandraTA-2b-instruct"
  device: "cuda"
  trust_remote_code: true

generation_params:
  max_new_tokens: 512
  temperature: 0.0
  repetition_penalty: 1.2
  top_k: 40
  top_p: 0.9
  no_repeat_ngram_size: 3
  num_beams: 5
  use_eos_token: true
  stop_sequences: ["<|im_end|>", "\nEnglish:", "###"]
