NLLB:
  #model: facebook/nllb-200-distilled-600M
  #model: facebook/nllb-200-distilled-1.3B
  model: facebook/nllb-200-1.3B
  #A HuggingFace repository folder for the  model or full or relative path to a local ./NLLB-FT-model
  src_lang: hrv_Latn
  tgt_lang: spa_Latn
  device: gpu
  beam_size: 5
  num_hypotheses: 5
